{% set python_min = "3.10" %}
{% set name = "geocat-viz" %}
{% set version = "2025.07.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/NCAR/geocat-viz/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: de66ada1359ba79fe52893a8347812e2d5233c3d1856cefd5a8d76b6375e87b1

build:
  noarch: python
  number: 0
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - cartopy
    - cmaps
    - matplotlib-base
    - metpy
    - packaging
    - pint
    - numpy
    - scikit-learn
    - xarray

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - geocat
    - geocat.viz
  commands:
    - pip check

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-viz is a collection of utility functions to make Python plotting with Matplotlib and Cartopy more like NCL (NCAR Command Language).
  dev_url: https://github.com/NCAR/geocat-viz
  doc_url: https://geocat-viz.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NCAR/geocat # GeoCAT https://github.com/orgs/NCAR/teams/geocat
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - jukent # J. Kent https://github.com/jukent/
    - kafitzgerald # K. FitzGerald https://github.com/kafitzgerald
